# syntax=docker/dockerfile:1

# Debian slim, NOT alpine. Prisma's query engine is a native binary linked against
# OpenSSL, and the musl build expects libssl.so.1.1 while node:*-alpine ships
# OpenSSL 3 — the container builds fine and then dies on first query with
# "Error loading shared library libssl.so.1.1". Alpine is workable via
# binaryTargets = ["linux-musl-openssl-3.0.x"], but it buys nothing here.

# ---- build stage ----
FROM node:22-slim AS build
WORKDIR /app

# Prisma's engine downloader needs CA certs.
RUN apt-get update && apt-get install -y --no-install-recommends openssl ca-certificates \
 && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
# Dev deps included on purpose: `prisma` (the CLI) is a devDependency and is what
# generates the client below.
RUN npm ci

# schema.prisma is COMMITTED, generated by `npm run pull` against a dev database.
# The build generates the client FROM that committed file — it never introspects
# and never migrates. `prisma db pull` and `prisma migrate` must not run here:
# migrate has no history for api/'s 50 tables, would read them as drift, and
# would offer to reset the production database.
COPY prisma ./prisma
RUN npx prisma generate

COPY . .
# Drop the dev deps now the client exists; the generated client lives in
# node_modules/.prisma and survives the prune.
RUN npm prune --omit=dev

# ---- runtime stage ----
FROM node:22-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends openssl ca-certificates \
 && rm -rf /var/lib/apt/lists/*

COPY --from=build --chown=node:node /app /app

# AdminJS bundles its frontend components into ./.adminjs on initialize(), which
# means the working directory has to be WRITABLE by the user we drop to.
#
# `COPY --chown` only sets ownership on the content it copies — /app itself was
# created by WORKDIR above and stays root-owned, so `node` could read every file
# and still not create a single new one. The failure is deferred and easy to miss:
# the process starts, /health answers, and it only dies on the first request that
# actually reaches the panel, with `EACCES: permission denied, mkdir '.adminjs'`.
RUN mkdir -p /app/.adminjs && chown -R node:node /app

USER node
ENV NODE_ENV=production
EXPOSE 8100

# DATABASE_URL and ADMIN_COOKIE_SECRET are injected at runtime, never baked in.
CMD ["node", "src/index.js"]
